# Generated by Django 3.1.3 on 2020-12-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginalscore', models.IntegerField(default=0)),
                ('highscore', models.IntegerField(default=0)),
            ],
        ),
    ]
