# Generated by Django 3.1.3 on 2020-12-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreinfomation',
            old_name='highscore',
            new_name='currentscore',
        ),
        migrations.RemoveField(
            model_name='scoreinfomation',
            name='orginalscore',
        ),
        migrations.AddField(
            model_name='scoreinfomation',
            name='is_proficient',
            field=models.CharField(choices=[('0', 'Proficient'), ('1', 'Almost Proficient'), ('2', 'Non-Proficient')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreinfomation',
            name='orginal_proficient',
            field=models.CharField(choices=[('0', 'Proficient'), ('1', 'Non-Proficient')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
