# Generated by Django 3.1.2 on 2020-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20201018_2314'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='classes.ClassModel'),
        ),
    ]
