# Generated by Django 3.1.2 on 2020-10-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': ['score_id'],
            },
        ),
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Have not started'), ('1', 'In progress'), ('2', 'Done')], max_length=1)),
                ('scoreinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tasks.scoreinfomation')),
            ],
        ),
    ]
