# Generated by Django 3.1.2 on 2020-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201101_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksassignedmodel',
            name='due_date',
            field=models.DateField(default=None),
        ),
    ]
