# Generated by Django 3.1.3 on 2020-11-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201106_0402'),
        ('tasks', '0004_tasksassignedmodel_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksassignedmodel',
            name='assigned_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='account.student'),
        ),
    ]
