# Generated by Django 3.1.3 on 2020-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201108_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksassignedmodel',
            name='scoreinfo',
            field=models.IntegerField(),
        ),
    ]
