# Generated by Django 3.1.3 on 2020-12-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201203_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksassignedmodel',
            old_name='scoreinfo',
            new_name='highestscore',
        ),
        migrations.AddField(
            model_name='tasksassignedmodel',
            name='orginalscore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
