# Generated by Django 3.1.3 on 2020-12-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tasksmodel_proficiency_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksassignedmodel',
            name='highestscore',
        ),
        migrations.RemoveField(
            model_name='tasksassignedmodel',
            name='orginalscore',
        ),
        migrations.AddField(
            model_name='tasksassignedmodel',
            name='scores_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Score_Prof_Info', to='tasks.scoreinfomation'),
            preserve_default=False,
        ),
    ]
