# Generated by Django 3.1.3 on 2020-12-08 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20201207_2355'),
        ('tasks', '0010_auto_20201208_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksassignedmodel',
            name='scores_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Score_Prof_Info', to='scores.scoreinfomation'),
        ),
        migrations.DeleteModel(
            name='ScoreInfomation',
        ),
    ]
