# Generated by Django 3.1.3 on 2021-10-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0031_proficiencylevel_subject'),
        ('tasks', '0011_auto_20201208_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('proficiency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_id', to='proficiencies.proficiency')),
            ],
        ),
    ]
