# Generated by Django 3.1.3 on 2021-11-08 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_subjectmodel_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0002_auto_20201207_2355'),
        ('tasks', '0012_assessmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmodel',
            name='url',
        ),
        migrations.CreateModel(
            name='AssessmentAssignedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Have not started'), ('1', 'In progress'), ('2', 'Done')], max_length=1)),
                ('due_date', models.DateField(default=None)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assessment', to='tasks.assessmentmodel')),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_id', to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Class_id', to='classes.classmodel')),
                ('scores_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Score_Assess_Info', to='scores.scoreinfomation')),
            ],
        ),
    ]
