# Generated by Django 3.1.3 on 2021-11-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20211108_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentassignedmodel',
            name='due_date',
        ),
    ]
