# Generated by Django 3.1.3 on 2021-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_assessmentassignedmodel_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentassignedmodel',
            name='scores_id',
        ),
        migrations.AddField(
            model_name='assessmentassignedmodel',
            name='proficient',
            field=models.CharField(choices=[('0', 'Not Proficient'), ('1', 'Almost Proficient'), ('2', 'Proficient')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='next_assessment',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='prev_assessment',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
