# Generated by Django 3.1.3 on 2021-11-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0033_proficiencylevel_proficient'),
        ('tasks', '0015_auto_20211111_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentassignedmodel',
            name='proficiency_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proficiencies.proficiencylevel'),
        ),
    ]
