# Generated by Django 3.1.2 on 2020-10-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='room',
            field=models.TextField(max_length=255),
        ),
    ]
