# Generated by Django 3.1.2 on 2020-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201016_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='class_id',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='class_id',
            field=models.ManyToManyField(to='classes.ClassModel'),
        ),
    ]
