# Generated by Django 3.1.2 on 2020-10-18 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_auto_20201018_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='class_id',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
