# Generated by Django 3.1.2 on 2020-11-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0005_auto_20201101_2003'),
        ('classes', '0007_auto_20201018_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='proficiencies',
            field=models.ManyToManyField(related_name='classes', to='proficiencies.Proficiency'),
        ),
    ]
