# Generated by Django 3.1.2 on 2020-11-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_classmodel_proficiencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='proficiencies',
        ),
    ]
