# Generated by Django 3.1.3 on 2020-12-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('classes', '0009_remove_classmodel_proficiencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='grades.grademodel'),
        ),
    ]
