# Generated by Django 3.1.3 on 2021-10-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('classes', '0011_auto_20201206_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grademodel')),
            ],
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='subject',
            field=models.ForeignKey(default='Math', on_delete=django.db.models.deletion.CASCADE, to='classes.subjectmodel'),
        ),
    ]
