# Generated by Django 3.1.3 on 2021-10-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20211013_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.subjectmodel'),
        ),
    ]
