# Generated by Django 3.1.3 on 2021-10-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20211013_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='grade',
        ),
    ]
