# Generated by Django 3.1.2 on 2020-11-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyModel',
            fields=[
                ('id', models.CharField(max_length=10,
                                        primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProficiencyLevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proficient', models.BooleanField()),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='Students', to='proficiencies.proficiencymodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='Proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
