# Generated by Django 3.1.2 on 2020-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiencymodel',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
