# Generated by Django 3.1.2 on 2020-11-01 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proficiencies', '0002_auto_20201101_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProficiencyModel',
            new_name='Proficiencies',
        ),
        migrations.RenameModel(
            old_name='ProficiencyLevelModel',
            new_name='ProficiencyLevels',
        ),
    ]
