# Generated by Django 3.1.2 on 2020-11-01 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proficiencies', '0003_auto_20201101_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proficiencies',
            new_name='Proficiency',
        ),
        migrations.RenameModel(
            old_name='ProficiencyLevels',
            new_name='ProficiencyLevel',
        ),
    ]
