# Generated by Django 3.1.2 on 2020-11-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0005_auto_20201101_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='long_description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
