# Generated by Django 3.1.3 on 2020-12-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('proficiencies', '0006_proficiency_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grade', to='grades.grademodel'),
        ),
    ]
