# Generated by Django 3.1.3 on 2020-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0007_auto_20201206_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiencylevel',
            name='is_proficient',
            field=models.CharField(choices=[('0', 'Proficient'), ('1', 'Almost Proficient'), ('2', 'Non-Proficient')], max_length=1),
        ),
    ]
