# Generated by Django 3.1.3 on 2020-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0009_auto_20201206_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='name',
            field=models.CharField(default='MATH-5.NF.1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
