# Generated by Django 3.1.3 on 2020-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0010_auto_20201207_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencylevel',
            name='currentscore',
            field=models.IntegerField(default=0),
        ),
    ]
