# Generated by Django 3.1.3 on 2020-12-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0011_proficiencylevel_currentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencylevel',
            name='orginal_proficient',
            field=models.CharField(choices=[('0', 'Proficient'), ('1', 'Non-Proficient')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
