# Generated by Django 3.1.3 on 2020-12-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0012_proficiencylevel_orginal_proficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiencylevel',
            name='currentscore',
        ),
        migrations.RemoveField(
            model_name='proficiencylevel',
            name='is_proficient',
        ),
        migrations.RemoveField(
            model_name='proficiencylevel',
            name='orginal_proficient',
        ),
    ]
