# Generated by Django 3.1.3 on 2020-12-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20201207_2355'),
        ('proficiencies', '0013_auto_20201207_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencylevel',
            name='scores_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Score_Info', to='scores.scoreinfomation'),
            preserve_default=False,
        ),
    ]
