# Generated by Django 3.1.3 on 2021-10-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0014_proficiencylevel_scores_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=20)),
                ('next_target', models.CharField(max_length=20)),
                ('prev_target', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='proficiency',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proficiencies.targetmodel'),
        ),
    ]
