# Generated by Django 3.1.3 on 2021-10-07 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20201206_0306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
        ('proficiencies', '0015_auto_20211006_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proficient', models.CharField(choices=[('0', 'Proficient'), ('1', 'Non-Proficient')], max_length=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Standard_Class_Info', to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StandardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('next_standard', models.CharField(max_length=20)),
                ('next_standardID', models.CharField(max_length=20)),
                ('prev_standard', models.CharField(max_length=20)),
                ('prev_standardID', models.CharField(max_length=20)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StandardGrade', to='grades.grademodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='target',
        ),
        migrations.DeleteModel(
            name='TargetModel',
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='proficiency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Standard_Proficiency_Info', to='proficiencies.proficiency'),
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Standard_Student_Info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proficiencies.standardmodel'),
        ),
    ]
