# Generated by Django 3.1.3 on 2021-10-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0016_auto_20211007_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardlevel',
            name='standard_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Standard_ID', to='proficiencies.standardmodel'),
        ),
    ]
