# Generated by Django 3.1.3 on 2021-10-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20211013_2146'),
        ('proficiencies', '0020_auto_20211013_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmodel',
            name='subject',
            field=models.ForeignKey(default='Math', on_delete=django.db.models.deletion.CASCADE, to='classes.subjectmodel'),
        ),
    ]
