# Generated by Django 3.1.3 on 2021-10-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0023_standardmodel_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardmodel',
            name='temp',
        ),
    ]
