# Generated by Django 3.1.3 on 2021-10-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20201207_2355'),
        ('proficiencies', '0024_remove_standardmodel_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardlevel',
            name='is_proficient',
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='scores_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Standard_Score_Info', to='scores.scoreinfomation'),
        ),
    ]
