# Generated by Django 3.1.3 on 2021-10-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0025_auto_20211014_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardmodel',
            name='temp',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
