# Generated by Django 3.1.3 on 2021-10-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('proficiencies', '0027_remove_standardmodel_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardlevel',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Standard_Grade', to='grades.grademodel'),
        ),
    ]
