# Generated by Django 3.1.3 on 2021-10-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_subjectmodel_grade'),
        ('proficiencies', '0028_standardlevel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subjectmodel'),
        ),
    ]
