# Generated by Django 3.1.3 on 2021-10-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_subjectmodel_grade'),
        ('proficiencies', '0030_standardlevel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencylevel',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.subjectmodel'),
        ),
    ]
