# Generated by Django 3.1.3 on 2021-11-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0031_proficiencylevel_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardlevel',
            name='scores_id',
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='proficient',
            field=models.CharField(choices=[('0', 'Not Proficient'), ('1', 'Almost Proficient'), ('2', 'Proficient')], default='0', max_length=1),
        ),
    ]
