# Generated by Django 3.1.3 on 2021-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proficiencies', '0032_auto_20211115_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencylevel',
            name='proficient',
            field=models.CharField(choices=[('0', 'Not Proficient'), ('1', 'Almost Proficient'), ('2', 'Proficient')], default='0', max_length=1),
        ),
    ]
